### ISSUE TITLE
Getting message "Please enable javascript" on login page

### ISSUE THREAD

**Issue by Rubonnek** [YunoHost-Apps/cockpit_ynh#16]
### Describe the bug

Getting message "Please enable javascript" on login page and I'm unable to access the Cockpit UI.

### Context

- Hardware: virtualized through QEMU
- YunoHost version: 
```
yunohost: 
  repo: stable
  version: 11.0.9.15
yunohost-admin: 
  repo: stable
  version: 11.0.10
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough:
    ```sh
    sudo yunohost app install cockpit
    ```
- Attempt to access cockpit through URL where it was installed

### Expected behavior

I would be greeted by the login page

### Logs

```
Oct 04 18:40:18 mydomain.tld cockpit-ws[4776]: cockpit-ws: couldn't load configuration file: /etc/cockpit/cockpit.conf: Permission denied
Oct 04 18:45:12 mydomain.tld cockpit-ws[5195]: cockpit-ws: Failed to open certificate file /run/cockpit/tls/e3b0c44298fc1c149afbf4c8996fb92427ae41e4>
```

*If applicable and useful, add screenshots to help explain your problem.*

### Possible fix / workaround

I was able to access Cockpit's login page after executing:

sudo chmod +r /etc/cockpit/cockpit.conf

**Comment by vinylourson** [comment]
Had the same issue after a fresh install.

Running `sudo chmod +r /etc/cockpit/cockpit.conf` did fix the issue for me as well.

**Comment by thomascwells** [comment]
Also fixed the issue for me.

**Comment by valterbarreira** [comment]
I'm still getting the javascript error, even after running that command. Fresh install on a subdomain.

**Comment by joeldebruijn** [comment]
Got the same error, checked diagnosis and services, Cockpit service stops every time after restarting the service.

**Comment by Graninius** [comment]
Had the same issue (fresh installed in subpath) but the command fixed it.

**Comment by joeldebruijn** [comment]
> Had the same issue after a fresh install.
> 
> Running `sudo chmod +r /etc/cockpit/cockpit.conf` did fix the issue for me as well.

I'm fairly new to this, but I understand chmod + r grants read permissions.
In the context of Yuno, does this mean the "cockpit" systemuser needs to get reading permissons?
Because this command didnt work for me out of the box.

**Comment by joeldebruijn** [comment]
After a clean cockpit install and using that command the permissions change from:

-r--r----- 1 root cockpit-ws cockpit.conf to

-r--r--r-- 1 root cockpit-ws cockpit.conf

After restarting the server I still get the same message.

**Comment by jcn50** [comment]
@ericgaspar why are those little bugs still not fixed after so long?...

**Comment by ericgaspar** [comment]
@jcn50 Why ping me? I'm not even the maintainer of this app. As far as i know, you are as responsible as me to fix these little bugs

**Comment by ericgaspar** [comment]
> who is the maintainer?

Toi, moi, quelqu'un, souvent personne... en l'occurrence pour cockpit, le mainteneur était liberodark mais il ne semble plus actif... Il faut comprendre que les contributions sont souvent sporadiques et limitées par le temps de chacun. Donc si tu as identifié un bug n’hésite pas à faire une PR. (pour info, le catalogue contient plus de 400 apps pour seulement une poignée de volontaires...)

**Comment by orhtej2** [comment]
This issue should have been fixed with https://github.com/YunoHost-Apps/cockpit_ynh/commit/bcb7e4ab67c4647452847ba00ef12b3ea8e53915, can you try upgrading normally and confirm if it helps?

**Comment by jcn50** [comment]
I am still having issues, getting 502 BAD GATEWAY on those:
https://$SUBDOMAIN/cockpit/static/login.js
https://$SUBDOMAIN/cockpit/static/login.css
https://$SUBDOMAIN/cockpit/static/branding.css
